"""added column real

Revision ID: f6c7c5cb9f3d
Revises: 6aab1a09589b
Create Date: 2025-11-09 02:30:52.750461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6c7c5cb9f3d'
down_revision: Union[str, Sequence[str], None] = '6aab1a09589b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('real', sa.String(), nullable=True))
    op.add_column('posts', sa.Column('credibility_score', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'credibility_score')
    op.drop_column('posts', 'real')
    # ### end Alembic commands ###
